# taken from: https://github.com/palladius/facebook-sdk
application: fb-cfs-python
version: facebook-sdk-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: example.app

# librerie di GAE: https://developers.google.com/appengine/docs/python/tools/libraries27
libraries:
- name: jinja2
  version: latest
#- name: requests
#  #url: https://github.com/pythonforfacebook/facebook-sdk
#  version: latest
